### PR TITLE
Mentors

### PR DESCRIPTION
**Pull request by marcol13**
Create mentors view

**Desktop**:

image

**Tablet**:

image

**Mobile**:

image

### CODE REVIEW

**Comment by marcol13** [comment]
Rebase trochę mi pomieszał w plikach i przypisał mi zaciągnięte z mastera zmiany, także sorki za zamieszanie w  PR 😅

**Comment by roertbb** [comment]
> Rebase makes a little mess in files and claim credits to me for all the changes pulled from `master` branch... I am sorry for these troubles 😅

Let's merge https://github.com/akai-org/akai-code/pull/41 and rebase that one / merge master to it - to highlihgt only the modified files and making the diff smaller

**Review by roertbb — APPROVED** [review]
One small nitpick - based on designs - Card component should have all corners rounded 😉

**Comment by marcol13** [comment]
> One small nitpick - based on designs - Card component should have all corners rounded 😉

Good point! Done in 211397b02489c17968196028a132402e59c22f38

image

**Pull request merged**
